Fix build on ARM: override set of libraries for linking dynamic_load_test
Copy in the same override that's in tests/hello_world/nacl.scons.

The default set of libraries fails to link, producing the error:
.../lib/libsrpc.a(accept_loop.o): In function `__srpc_init':
.../srpc/accept_loop.o.opt.bc:(.text+0x2cc): undefined reference to `pthread_create'
.../srpc/accept_loop.o.opt.bc:(.text+0x2dc): undefined reference to `pthread_detach'

Breakage was introduced by r2033.

Review URL: http://codereview.chromium.org/1618018

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@2034 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2