Revert of Change some source_sets to static_library to shrink binary (patchset #1 id:1 of https://codereview.chromium.org/2519103003/ )
Reason for revert:
It looks like this fails when rolled into Chromium, with this error:

Undefined symbols for architecture x86_64:
  "_NaClSwitch", referenced from:
      _NaClSyscallSegRegsSaved in nacl_syscall_64.o
     (maybe you meant: _NaClSwitchAVX, _NaClSwitchSSE )
  "_nacl_current_thread_tls_offset", referenced from:
      _NaClSyscallSeg in nacl_syscall_64.o
      _NaClGetTlsFastPath1 in nacl_syscall_64.o
      _NaClGetTlsFastPath1End in nacl_syscall_64.o
ld: symbol(s) not found for architecture x86_64

from:
https://build.chromium.org/p/tryserver.chromium.mac/builders/mac_chromium_com...
https://codereview.chromium.org/2523593005/

with these gn settings:

goma_dir = "/b/c/cipd/goma"
is_component_build = true
is_debug = true
symbol_level = 1
use_goma = true

Original issue's description:
> Change some source_sets to static_library to shrink binary
>
> The gn generated binaries are bigger than the gyp generated binaries.
> One of the known differences was due to the nacl_global_rng and
> g_NaCl_log_gio global variables which are in gn's chrome.dll but not in
> gyp's. In some cases these global variables can serve as effective
> canaries - removing them can lead to much code going away as well.
>
> Changing from source_set to static_library means that the linker is not
> required to link in the associated .obj files, which can save time and
> space.
>
> In this case no code was removed so the space savings was small - just
> the 1.5 KB of space consumed by the globals.
>
> R=phosek@chromium.org
> BUG=630755
>
> Committed: https://chromium.googlesource.com/native_client/src/native_client/+/508aaa7b011729ee6eaab3384b89a7bfd0ecba73

TBR=phosek@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=630755

Review-Url: https://codereview.chromium.org/2525583003