Add missing "#include <iterator>"
This is necessary to build on Visual Studio 2010 Express.

This fixes the error:
src\trusted\nonnacl_util\sel_ldr_launcher.cc(217) : error C3861: 'back_inserter': identifier not found
src\trusted\nonnacl_util\sel_ldr_launcher.cc(218) : error C3861: 'back_inserter': identifier not found

MSDN docs say "back_inserter" is defined in <iterator>.

BUG=http://code.google.com/p/nativeclient/issues/detail?id=1287
TEST=trybots

Review URL: http://codereview.chromium.org/5995008

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@4052 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2