Update revision for Saigo
Update 48ef8680df38e3484d14ed28f97a383aaba033ed -> 99f2552944a668f9e7f61b8d8cae77b72d63a9b1

Pull the following Saigo changes into NaCl:
  99f2552: (fabiansommer@chromium.org) Rebase saigo

The new revision introduces -Wcast-function-type-mismatch as default,
which needs to be disabled in two places.
Otherwise, this triggers at nacl_threads.c:69:35:
error: cast from 'void (*)(void *)' to 'void *(*)(void *)'
(void *(*)(void *)) start_fn
^~~~~~~~~~~~~~~~~~~~~~~~~~~~

BUG= <none>
R= fabiansommer@chromium.org
TEST=git cl try
(Please LGTM this change and tick the "commit" box)

Change-Id: I0b55e0a691993e344e46136580919066f7015363
Reviewed-on: https://chromium-review.googlesource.com/c/native_client/src/native_client/+/5442857
Reviewed-by: Derek Schuff <dschuff@chromium.org>
Auto-Submit: Fabian Sommer <fabiansommer@chromium.org>
Commit-Queue: Derek Schuff <dschuff@chromium.org>