Windows: Fix process/thread exit race condition that makes many tests flaky
On the Windows bots, a lot of the NaCl tests fail
non-deterministically with the error:

  ERROR: Command returned exit status 255 (0xff) but we expected 0 (0x0)

This is because we are using TerminateProcess() to exit, which
terminates all threads in a non-deterministic order.  On Windows, the
exit status of a process is taken to be the exit status of the last
thread that exited.  Using TerminateProcess() therefore makes the exit
status of the process unreliable.

The 0xff value comes from nap->exit_status' initial value of -1.  If a
NaClAppThread starts to exit before NaCl's exit() syscall has been
called, it will read nap->exit_status as -1, which it masks to 0xff.

Using ExitProcess() instead will avoid this problem, because it
terminates the calling thread last.

This has already proven itself for run_multidomain_test.  I switched
that to using ExitProcess() and it eliminated the exit status flake
for that test.

BUG=https://code.google.com/p/nativeclient/issues/detail?id=2870
TEST=trybots

Review URL: https://codereview.chromium.org/11549013

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@10447 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2